BUSD_SYMBOL = 'BNB.BUSD-BD1'
BUSD_SYMBOL_TEST = 'BNB.BUSD-BAF'

USDT_BNB_SYMBOL = 'BNB.USDT-6D8'
USDT_BNB_SYMBOL_TEST = 'BNB.USDT-6D8'
USDT_ETH_SYMBOL_TEST = 'ETH.USDT-0X62E273709DA575835C7F6AEF4A31140CA5B1D190'

RUNE_SYMBOL_BNB = 'BNB.RUNE-B1A'
RUNE_SYMBOL_BNB_TEST = 'BNB.RUNE-67C'

RUNE_SYMBOL_NATIVE = 'THOR.RUNE'
RUNE_SYMBOL = RUNE_SYMBOL_BNB

RUNE_SYMBOLS = (
    RUNE_SYMBOL_BNB,
    RUNE_SYMBOL_BNB_TEST,
    RUNE_SYMBOL_NATIVE,
)


def is_rune(symbol):
    return symbol in RUNE_SYMBOLS


STABLE_COINS = (
    BUSD_SYMBOL, BUSD_SYMBOL_TEST,
    USDT_BNB_SYMBOL, USDT_BNB_SYMBOL_TEST,
    USDT_ETH_SYMBOL_TEST
)


def is_stable_coin(symbol):
    return symbol in STABLE_COINS
