version: '3.3'

volumes:
    db_data: {}

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - .env/:/app/.env
    restart: on-failure
    env_file: .env

  frontend:
    image: node:14-alpine
    command: npm run serve
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
    working_dir: /app
    restart: on-failure

  db:
    image: "postgres:latest"
    restart: always
    ports:
      - 54320:5432
    env_file: .env
    volumes:
      - ./db_data:/var/lib/postgresql/data/chaos
    environment:
      PGDATA: /var/lib/postgresql/data/chaos/

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
