version: '3.3'

volumes:
    db_data: {}
    letsencrypt:

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - .env/:/app/.env
    restart: on-failure
    env_file: .env

  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: .env

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./frontend/dist/:/dist/
    environment:
      CERTBOT_EMAIL: myemail@tirinox.ru
#    logging:
#      driver: none
