version: '3.3'

volumes:
    postgres_data: {}


services:

  #  postgres:
  #    image: postgres:10-alpine
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #    env_file: .env

  backend:
    build:
      context: ./backend
#    depends_on:
#      - postgres
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    restart: on-failure
    env_file: .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
#    logging:
#      driver: none
    # make sure nginx restarts every 6h
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

